### ISSUE TITLE
question on loading the p12 file.

### ISSUE THREAD

**Issue by danoyoung** [pingles/googlecloud#13]
How do you recommend loading the p12 file from the JAR file?  It seems that .setServiceAccountPrivateKeyFromP12File requires a file path and I'm having problems trying to figure out how to get this out of the jar when running an uberjar.   Works fine in the REPL or when I have the file on the filesystem.  When I try to run the java -jar command, I get this exception:

Caused by: java.lang.IllegalArgumentException: Not a file: jar:file: .....

How do you guys recommend handling this since I would like to bundle the p12 file with the jar?

Regards,

Dano

**Comment by pingles** [comment]
Hi Dan,

I'm not sure whether this is possible. The Google client expects a File
instance and I don't think there's a way of accessing resources via the
class loader as a file. I accidentally found a GitHub issue related to what
you're asking: https://github.com/google/google-api-java-client/issues/857

We don't distribute keys in the uberjars. Most of the time we use Vault (
https://www.vaultproject.io/) to store secrets (such as credential files)
and distribute to the different app servers and processes. Is there a
reason you're trying to put it all into an uberjar?

Paul

**Comment by danoyoung** [comment]
Hey Paul,

Thank you for the prompt reply. I saw that same issue, so I was curious if this was/is even possible. I'm trying to run this in AWS Lambda. Since there's no servers involved, I though bundling the key in the jar would be a way (not sure if it's the right way though). Let me look into the AWS Lambda docs again in more detail, they do make 500MB in /tmp available.

**Comment by danoyoung** [comment]
Hey Paul, just a FYI, 

I switched over to using the .setServiceAccountPrivateKey within the service credentials.  It required some small tweaks and calling the loadPrivateKeyFromKeyStore within the com.google.api.client.util SecurityUtils.  Seems to work fine now loading from S3, will be looking into moving this to possible AWS KMS.  Thanx!

Regards,

Dano

**Comment by pingles** [comment]
Cool! If you can work the changes into a PR that'd be good to see/integrate
some time :)

**Comment by danoyoung** [comment]
Sounds good.  Let me get all this voodoo magic working.
